
name: Install Cog
description: Install Cog so you can run, test, and push machine learning models to Replicate.
author: replicate
branding:
  icon: terminal
  color: gray-dark

inputs:
  replicate_api_token:
    required: true
    description: "If present, this token is used to authenticate to Replicate using `cog login` so you can push your model."
  cog_version:
    description: "The version of Cog to install"
    required: false
    # This version of Cog adds support for `cog run` on non-GPU environments (like GitHub Actions' default runners)
    default: "v0.8.0-beta3"

runs:
  using: "composite"
  steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Install NVIDIA CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.10

      - name: Install Cog
        shell: bash
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/${{ inputs.cog_version }}/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Log in to Replicate
        shell: bash
        if: ${{ inputs.replicate_api_token != '' }}
        env:
          REPLICATE_API_TOKEN: ${{ inputs.replicate_api_token }}
        run: |
          echo "Found REPLICATE_API_TOKEN in the environment; Authenticating..."
          echo $REPLICATE_API_TOKEN | cog login --token-stdin