
name: Push model to Replicate
description: Install Cog and push a model to Replicate
inputs:
  model_name:
    required: true
    description: "The name of the Replicate model to publish, e.g `username/modelname`. The model must already exist on Replicate."
  replicate_api_token:
    required: true
    description: "The Replicate API token."
  cog_version:
    description: "The version of Cog to use"
    required: false
    # This version of Cog adds support for `cog run` on non-GPU environments (like GitHub Actions' default runners)
    default: "v0.8.0-beta3"
  prepush_script:
    description: "Filename of a script to `cog run` before pushing to Replicate, e.g. `script/download-weights`"
    required: false

runs:
  using: "composite"
  steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Install NVIDIA CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.10

      - name: Install Cog
        shell: bash
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/download/${{ inputs.cog_version }}/cog_Linux_x86_64
          sudo chmod +x /usr/local/bin/cog
          cog --version

      - name: Log in to Replicate
        shell: bash
        env:
          REPLICATE_API_TOKEN: ${{ inputs.replicate_api_token }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin

      - name: Run prepush script
        if: ${{ inputs.prepush_script != "" }}
        shell: bash
        run: |
          cog run ${{ inputs.prepush_script }}

      - name: Push to Replicate
        shell: bash
        run: |
          cog push r8.im/${{ inputs.model_name }}